import './globals.css';
import Navigation from '@/lib/components/navigation';

export const metadata = {
    title: 'Welcome to demo2',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="light">
            <body>
                <div className="mx-auto flex min-h-screen w-full flex-col items-center bg-slate-200">
                    <div className="container flex max-w-6xl flex-col items-stretch">
                        <div className="flex items-center justify-center">
                            <Navigation />
                        </div>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
